//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "НомПосылки as \'Номер посылки\'",
            "НомерПост as \'Номер постамата\'",
            "НомерЯчейки as \'Номер ячейки\'",
            "Транзакция as \'Транзакция\'",
            "Логистика.Информация as \'Информация\'",
            "Транзакция.Дата as \'Дата оплаты\'",
            "Транзакция.Время as \'Время оплаты\'",
            "Транзакция.Оплата as \'Статус оплаты\'",
            "Транзакция.Сумма as \'Сумма\'",
            "Логистика as \'Логистика\'",
            "Код as \'Код\'",
            "Код.СгенКод as \'Сгенерировать код\'"}, Hidden=new string[] {
            "Логистика.Информация",
            "Транзакция.Время",
            "Код.СгенКод"})]
    [MasterViewDefineAttribute("ПосылкаE", "Транзакция", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    [MasterViewDefineAttribute("ПосылкаE", "Логистика", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Информация")]
    [MasterViewDefineAttribute("ПосылкаE", "Код", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СгенКод")]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПост;
        
        private int fНомПосылки;
        
        private int fНомерЯчейки;
        
        private IIS.Postamat.Транзакция fТранзакция;
        
        private IIS.Postamat.Логистика fЛогистика;
        
        private IIS.Postamat.Код fКод;
        
        private IIS.Postamat.Хранение fХранение;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// НомерПост.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерПост CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерПост CustomAttributes)
        public virtual int НомерПост
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерПост Get start)

                // *** End programmer edit section *** (Посылка.НомерПост Get start)
                int result = this.fНомерПост;
                // *** Start programmer edit section *** (Посылка.НомерПост Get end)

                // *** End programmer edit section *** (Посылка.НомерПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерПост Set start)

                // *** End programmer edit section *** (Посылка.НомерПост Set start)
                this.fНомерПост = value;
                // *** Start programmer edit section *** (Посылка.НомерПост Set end)

                // *** End programmer edit section *** (Посылка.НомерПост Set end)
            }
        }
        
        /// <summary>
        /// НомерЯчейки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомерЯчейки CustomAttributes)
        public virtual int НомерЯчейки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get start)
                int result = this.fНомерЯчейки;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Get end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set start)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set start)
                this.fНомерЯчейки = value;
                // *** Start programmer edit section *** (Посылка.НомерЯчейки Set end)

                // *** End programmer edit section *** (Посылка.НомерЯчейки Set end)
            }
        }
        
        /// <summary>
        /// НомПосылки.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.НомПосылки CustomAttributes)

        // *** End programmer edit section *** (Посылка.НомПосылки CustomAttributes)
        public virtual int НомПосылки
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.НомПосылки Get start)

                // *** End programmer edit section *** (Посылка.НомПосылки Get start)
                int result = this.fНомПосылки;
                // *** Start programmer edit section *** (Посылка.НомПосылки Get end)

                // *** End programmer edit section *** (Посылка.НомПосылки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.НомПосылки Set start)

                // *** End programmer edit section *** (Посылка.НомПосылки Set start)
                this.fНомПосылки = value;
                // *** Start programmer edit section *** (Посылка.НомПосылки Set end)

                // *** End programmer edit section *** (Посылка.НомПосылки Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Код CustomAttributes)

        // *** End programmer edit section *** (Посылка.Код CustomAttributes)
        [PropertyStorage(new string[] {
                "Код"})]
        [NotNull()]
        public virtual IIS.Postamat.Код Код
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Код Get start)

                // *** End programmer edit section *** (Посылка.Код Get start)
                IIS.Postamat.Код result = this.fКод;
                // *** Start programmer edit section *** (Посылка.Код Get end)

                // *** End programmer edit section *** (Посылка.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Код Set start)

                // *** End programmer edit section *** (Посылка.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Посылка.Код Set end)

                // *** End programmer edit section *** (Посылка.Код Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Логистика CustomAttributes)

        // *** End programmer edit section *** (Посылка.Логистика CustomAttributes)
        [PropertyStorage(new string[] {
                "Логистика"})]
        [NotNull()]
        public virtual IIS.Postamat.Логистика Логистика
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Логистика Get start)

                // *** End programmer edit section *** (Посылка.Логистика Get start)
                IIS.Postamat.Логистика result = this.fЛогистика;
                // *** Start programmer edit section *** (Посылка.Логистика Get end)

                // *** End programmer edit section *** (Посылка.Логистика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Логистика Set start)

                // *** End programmer edit section *** (Посылка.Логистика Set start)
                this.fЛогистика = value;
                // *** Start programmer edit section *** (Посылка.Логистика Set end)

                // *** End programmer edit section *** (Посылка.Логистика Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Транзакция CustomAttributes)

        // *** End programmer edit section *** (Посылка.Транзакция CustomAttributes)
        [PropertyStorage(new string[] {
                "Транзакция"})]
        [NotNull()]
        public virtual IIS.Postamat.Транзакция Транзакция
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Get start)

                // *** End programmer edit section *** (Посылка.Транзакция Get start)
                IIS.Postamat.Транзакция result = this.fТранзакция;
                // *** Start programmer edit section *** (Посылка.Транзакция Get end)

                // *** End programmer edit section *** (Посылка.Транзакция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Set start)

                // *** End programmer edit section *** (Посылка.Транзакция Set start)
                this.fТранзакция = value;
                // *** Start programmer edit section *** (Посылка.Транзакция Set end)

                // *** End programmer edit section *** (Посылка.Транзакция Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Postamat.Хранение.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Хранение CustomAttributes)

        // *** End programmer edit section *** (Посылка.Хранение CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Хранение"})]
        public virtual IIS.Postamat.Хранение Хранение
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Хранение Get start)

                // *** End programmer edit section *** (Посылка.Хранение Get start)
                IIS.Postamat.Хранение result = this.fХранение;
                // *** Start programmer edit section *** (Посылка.Хранение Get end)

                // *** End programmer edit section *** (Посылка.Хранение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Хранение Set start)

                // *** End programmer edit section *** (Посылка.Хранение Set start)
                this.fХранение = value;
                // *** Start programmer edit section *** (Посылка.Хранение Set end)

                // *** End programmer edit section *** (Посылка.Хранение Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Postamat.Посылка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Посылка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)
    public class DetailArrayOfПосылка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Postamat.DetailArrayOfПосылка members)

        // *** End programmer edit section *** (IIS.Postamat.DetailArrayOfПосылка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Посылка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Посылка.
        /// </summary>
        public DetailArrayOfПосылка(IIS.Postamat.Хранение fХранение) : 
                base(typeof(Посылка), ((ICSSoft.STORMNET.DataObject)(fХранение)))
        {
        }
        
        public IIS.Postamat.Посылка this[int index]
        {
            get
            {
                return ((IIS.Postamat.Посылка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Postamat.Посылка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
